services:
  - type: web
    name: yt-weak-current-system
    runtime: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: yt-weak-current-db
          property: connectionString

databases:
  - name: yt-weak-current-db
    plan: free
