services:
  - type: web
    name: yt-v316-render-free
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    healthCheckPath: /health
    envVars:
      - key: DB_URL
        sync: false
      - key: LINE_TOKEN
        sync: false
